In [10]:
#Loading required libraries

import numpy as np
import pandas as pd

In [6]:
#Import the dataset

headernames = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'Class']

iris=pd.read_csv("C:\\Users\\SANDHYA\\Downloads\\Datasets\\iris.data",names=headernames)
iris

sepal-length  sepal-width  petal-length  petal-width           Class
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [9]:
#Splitting into train & test sets as it is "Supervised Learning"

X=iris.iloc[:,:-1].values
y=iris.iloc[:,4].values

In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.30)

In [15]:
#From scikit-learn, run the classifier

from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier(n_estimators=50)
classifier.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=50,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [18]:
#Predict the results

y_pred=classifier.predict(X_test)

In [21]:
#Results

from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
result=confusion_matrix(y_test,y_pred)
print("Confusion matrix:")
print(result)

result1=classification_report(y_test,y_pred)
print("Classification report:")
print(result1)

result2=accuracy_score(y_test,y_pred)
print("Accuracy Score:")
print(result2)

Confusion matrix:
[[15  0  0]
 [ 0 15  1]
 [ 0  0 14]]
Classification report:
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        15
Iris-versicolor       1.00      0.94      0.97        16
 Iris-virginica       0.93      1.00      0.97        14

       accuracy                           0.98        45
      macro avg       0.98      0.98      0.98        45
   weighted avg       0.98      0.98      0.98        45

Accuracy Score:
0.9777777777777777
